SELECT ?method ?priority
WHERE {
  GRAPH <planner> {
    * cogrob:hasMethod ?method .
    ?method cogrob:hasPriority ?priority .
    ?method cogrob:hasCondition ?precond .
    ?precond cogrob:isMet "true"^^xsd:boolean
  }
}
