SELECT ?action ?actionClass ?target ?commitment
WHERE {
  ?action cogrob:isCausedBy * .
  ?action cogrob:actsOn ?target .
  ?action rdf:type ?actionType .
  ?actionType rdfs:subClassOf ?actionClass.
  NOT EXISTS {
    ?action cogrob:isCompleted "true"^^xsd:boolean .
  }
  FILTER (
    ?actionClass IN (cogrob:ArmEvent, cogrob:GripperEvent )
  ) .
}
