# A custom controller for test
test_controller:
    type: cobot_controllers/CartesianPoseController
    arm_id: panda

velocity_controller:
    type: cobot_controllers/CartesianVelocityController
    arm_id: panda

joint_position_controller:
    type: cobot_controllers/JointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

cartesian_impedance_controller:
    type: cobot_controllers/CartesianImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
