# A custom controller for test


cartesian_pose_controller:
    type: cobot_controllers/CartesianPoseController
    joint_names:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

joint_position_controller:
    arm_id: panda
    type: cobot_controllers/JointPositionController
    joint_names:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

test_controller:
    type: cobot_controllers/JointVelocityController
    joint_names:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7


insertion_controller:
    arm_id: panda
    type: cobot_controllers/CartesianImpedanceController
    joint_names:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7


cartesian_velocity_controller:
    type: cobot_controllers/CartesianVelocityController
    arm_id: panda

joint_position_controller:
    type: cobot_controllers/JointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7


elbow_controller:
    type: cobot_controllers/ElbowController
    arm_id: panda
