#!/usr/bin/env python

from sem_memory.srv import AddData, AddDataResponse
import rospy

def handle_add_data(req):
    print "Adding [%s]"%(req.fake_new_data)
    return AddTwoIntsResponse(1, "Successful")

def start_memory_server():
    rospy.init_node('memory_server')
    s = rospy.Service('add_two_ints', AddData, handle_add_data)
    print "Memory initialized."
    rospy.spin()

if __name__ == "__main__":
    start_memory_server()
